### ISSUE TITLE
Documentation compilation disabled by default

### ISSUE THREAD

**Issue by mailhexu** [nomad-coe/greenX#49]
In the README.md, "GreenX is documented using Doxygen, and documentation support is enabled by default."
But in the cmake file it seems to be disabled by default. I could only build the documentations by manually switching it to ON.

**Comment by AlexBuccheri** [comment]
If documentation were on by default, the  lack of an available doxygen package on a given system would break the build. Doxygen should be an optional dependency.

@AlexBuccheri 

- [ ] Update documentation stating that documentation is off by default.
