### ISSUE TITLE
Add short description, tags, and possibly website to the repo

### ISSUE THREAD

**Issue by Panadestein** [nomad-coe/greenX#59]
Hello, as the title suggest, it would be nice to add a short sentence summarizing what Green-X is, and also tags to the GitHub repository. We could also link the NOMAD website there (or ideally deploy a GitHub pages there). See the image below, this is empty in our repo:

![image](https://github.com/nomad-coe/greenX/assets/15854703/99cecb72-bc0e-4080-9c70-03ce35c709b2)

This is a very common thing, and it helps to project gain visibility. Unfortunately, I do not have permission to do it myself. Can you take care of it @aziziph or @AlexBuccheri ?

**Comment by aziziph** [comment]
Hello, Do you propose this structure as a WIKI for our repository?

**Comment by Panadestein** [comment]
No, for the moment only adding a description. If you have the permissions, you should be able to directly edit the `About` section on GitHub.

**Comment by aziziph** [comment]
I think only @AlexBuccheri has permission to edit.

**Comment by Panadestein** [comment]
Ping to @AlexBuccheri then.

**Comment by AlexBuccheri** [comment]
Yep, I have owner rights so I could assign repo settings.  Do you have a suggestion regarding the blurb?


>  link the NOMAD website there

No problem

> or ideally deploy a GitHub pages there

Could you clarify what you mean?

**Comment by Panadestein** [comment]
Oh, one could do a per-project GitHub [pages](https://pages.github.com/), but it does not have to be, it is only an idea. These pages are easy to set, and there are a bunch of Jekyll templates to choose from.

**Comment by Panadestein** [comment]
Judging from the last comment from our editor @lucydot, this issue just gained in relevance. @AlexBuccheri @aziziph @fdelesma @dgolze please let's discuss this further.
